[phases.setup]
nixPkgs = ["php84", "php84Extensions.pgsql", "php84Extensions.intl", "php84Extensions.mbstring", "php84Extensions.xml", "php84Extensions.curl", "php84Extensions.zip", "php84Extensions.gmp"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = ["php bin/console cache:clear --env=prod"]

[start]
cmd = "php -S 0.0.0.0:8080 -t public"
